version: '3.8'
services:
  trading-gateway:
    build:
      context: .
      dockerfile: services/trading_gateway/Dockerfile.dev
    container_name: trading_gateway
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./services/trading_gateway/.env
    networks:
      - exchange-network
    depends_on:
      - trading-gateway-redis
      - exchange-redis
  
  order-matching-engine:
    build:
      context: ./services/order_matching_engine
      dockerfile: Dockerfile.dev
    container_name: order_matching_engine
    restart: always
    env_file:
      - ./services/order_matching_engine/.env
    networks:
      - exchange-network
    depends_on:
      - exchange-redis

  trading-gateway-redis:
    image: redis:7
    container_name: trading_gateway_redis
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - trading_gateway_redis_data:/data
    networks:
      - exchange-network
    command: redis-server # No password here for dev.
    
  exchange-redis:
    image: redis:7
    container_name: exchange_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - exchange_redis_data:/data
    networks:
      - exchange-network
    command: redis-server # No password here for dev.

volumes:
  trading_gateway_redis_data:
  exchange_redis_data:

networks:
  exchange-network:
    driver: bridge
