version: '3.8'
services:
  trading-gateway:
    build:
      context: ./services/trading_gateway
      dockerfile: Dockerfile.dev
    container_name: trading_gateway
    restart: always
    command: ./bin/docker-entrypoint.dev.sh
    ports:
      - "8000:8000"
    env_file:
      - ./services/trading_gateway/.env
    networks:
      - exchange-network

networks:
  exchange-network:
    driver: bridge
